<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AdminMenusSeeder extends Seeder
{
    /**
     * 运行数据库填充
     */
    public function run(): void
    {
        $menus = [
            [
                'id' => 1,
                'parent_id' => 0,
                'title' => '首页',
                'icon' => 'ph:chart-line-up-fill',
                'url' => '/dashboard',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 1,
                'component' => null,
                'is_full' => 0,
                'extension' => null,
                'created_at' => null,
                'updated_at' => null,
                'keep_alive' => null,
                'iframe_url' => null,
                'custom_order' => 0,
            ],
            [
                'id' => 2,
                'parent_id' => 0,
                'title' => '系统管理',
                'icon' => 'material-symbols:settings-outline',
                'url' => '/system',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'component' => null,
                'is_full' => 0,
                'extension' => null,
                'created_at' => null,
                'updated_at' => '2023-01-31 06:54:21',
                'keep_alive' => null,
                'iframe_url' => null,
                'custom_order' => 20,
            ],
            [
                'id' => 3,
                'parent_id' => 2,
                'title' => '管理员',
                'icon' => 'ph:user-gear',
                'url' => '/system/admin_users',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'component' => null,
                'is_full' => 0,
                'extension' => null,
                'created_at' => null,
                'updated_at' => null,
                'keep_alive' => null,
                'iframe_url' => null,
                'custom_order' => 0,
            ],
            [
                'id' => 4,
                'parent_id' => 2,
                'title' => '角色',
                'icon' => 'carbon:user-role',
                'url' => '/system/admin_roles',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'component' => null,
                'is_full' => 0,
                'extension' => null,
                'created_at' => null,
                'updated_at' => null,
                'keep_alive' => null,
                'iframe_url' => null,
                'custom_order' => 10,
            ],
            [
                'id' => 5,
                'parent_id' => 2,
                'title' => '权限',
                'icon' => 'fluent-mdl2:permissions',
                'url' => '/system/admin_permissions',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'component' => null,
                'is_full' => 0,
                'extension' => null,
                'created_at' => null,
                'updated_at' => null,
                'keep_alive' => null,
                'iframe_url' => null,
                'custom_order' => 20,
            ],
            [
                'id' => 6,
                'parent_id' => 2,
                'title' => '菜单',
                'icon' => 'ant-design:menu-unfold-outlined',
                'url' => '/system/admin_menus',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'component' => null,
                'is_full' => 0,
                'extension' => null,
                'created_at' => null,
                'updated_at' => null,
                'keep_alive' => null,
                'iframe_url' => null,
                'custom_order' => 30,
            ],
            [
                'id' => 8,
                'parent_id' => 0,
                'title' => 'Json示例',
                'icon' => 'material-symbols:border-all-rounded',
                'url' => '/example',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'component' => null,
                'is_full' => 0,
                'extension' => null,
                'created_at' => '2022-09-06 10:32:40',
                'updated_at' => '2023-01-31 06:54:21',
                'keep_alive' => null,
                'iframe_url' => null,
                'custom_order' => 10,
            ],
            [
                'id' => 9,
                'parent_id' => 8,
                'title' => '所有Form示例',
                'icon' => 'ph:circle',
                'url' => '/example/form_all',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'component' => null,
                'is_full' => 0,
                'extension' => null,
                'created_at' => '2022-09-06 10:34:10',
                'updated_at' => '2022-09-06 11:05:12',
                'keep_alive' => null,
                'iframe_url' => null,
                'custom_order' => 0,
            ],
            [
                'id' => 10,
                'parent_id' => 8,
                'title' => '表单展示模式',
                'icon' => 'ph:circle',
                'url' => '/example/form',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'component' => null,
                'is_full' => 0,
                'extension' => null,
                'created_at' => '2022-09-06 11:05:57',
                'updated_at' => '2022-09-06 11:05:57',
                'keep_alive' => null,
                'iframe_url' => null,
                'custom_order' => 10,
            ],
            [
                'id' => 11,
                'parent_id' => 8,
                'title' => '显隐切换示例',
                'icon' => 'ph:circle',
                'url' => '/example/reaction',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'component' => null,
                'is_full' => 0,
                'extension' => null,
                'created_at' => '2022-09-06 11:16:26',
                'updated_at' => '2022-09-06 11:16:34',
                'keep_alive' => null,
                'iframe_url' => null,
                'custom_order' => 20,
            ],
            [
                'id' => 12,
                'parent_id' => 8,
                'title' => '条件生成器',
                'icon' => 'ph:circle',
                'url' => '/example/condition_builder',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'component' => null,
                'is_full' => 0,
                'extension' => null,
                'created_at' => '2022-09-06 11:20:12',
                'updated_at' => '2022-09-06 11:20:12',
                'keep_alive' => null,
                'iframe_url' => null,
                'custom_order' => 30,
            ],
            [
                'id' => 13,
                'parent_id' => 8,
                'title' => '弹框',
                'icon' => 'ph:circle',
                'url' => '/example/dialog',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'component' => null,
                'is_full' => 0,
                'extension' => null,
                'created_at' => '2022-09-06 11:23:46',
                'updated_at' => '2022-09-06 11:23:46',
                'keep_alive' => null,
                'iframe_url' => null,
                'custom_order' => 40,
            ],
            [
                'id' => 14,
                'parent_id' => 8,
                'title' => '选项卡',
                'icon' => 'ph:circle',
                'url' => '/example/tabs',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'component' => null,
                'is_full' => 0,
                'extension' => null,
                'created_at' => '2022-09-06 11:23:46',
                'updated_at' => '2022-09-06 11:23:46',
                'keep_alive' => null,
                'iframe_url' => null,
                'custom_order' => 50,
            ],
            [
                'id' => 15,
                'parent_id' => 8,
                'title' => '步骤表单',
                'icon' => 'ph:circle',
                'url' => '/example/wizard',
                'url_type' => 1,
                'visible' => 1,
                'is_home' => 0,
                'component' => null,
                'is_full' => 0,
                'extension' => null,
                'created_at' => '2022-09-06 11:23:46',
                'updated_at' => '2022-09-06 11:23:46',
                'keep_alive' => null,
                'iframe_url' => null,
                'custom_order' => 60,
            ],
        ];

        DB::table('admin_menus')->insert($menus);
    }
}
